// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShareCircle.Data;

#nullable disable

namespace ShareCircle.Migrations
{
    [DbContext(typeof(ShareCircleDbContext))]
    [Migration("20241116144754_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShareCircle.Models.ClanSkupine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumPridruzitve")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_skupine")
                        .HasColumnType("int");

                    b.Property<int>("ID_uporabnika")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_skupine");

                    b.HasIndex("ID_uporabnika");

                    b.ToTable("ClanSkupine");
                });

            modelBuilder.Entity("ShareCircle.Models.RazdelitevStroska", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_dolznika")
                        .HasColumnType("int");

                    b.Property<int>("ID_stroska")
                        .HasColumnType("int");

                    b.Property<float>("Znesek")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("ID_dolznika");

                    b.HasIndex("ID_stroska");

                    b.ToTable("RazdelitevStroska");
                });

            modelBuilder.Entity("ShareCircle.Models.Skupina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumNastanka")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImeSkupine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Skupina");
                });

            modelBuilder.Entity("ShareCircle.Models.Strosek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("CelotniZnesek")
                        .HasColumnType("real");

                    b.Property<DateTime>("DatumPlacila")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_placnika")
                        .HasColumnType("int");

                    b.Property<int>("ID_skupine")
                        .HasColumnType("int");

                    b.Property<int>("StevilkaStroska")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_placnika");

                    b.HasIndex("ID_skupine");

                    b.ToTable("Strosek");
                });

            modelBuilder.Entity("ShareCircle.Models.Uporabnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Priimek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Uporabnik");
                });

            modelBuilder.Entity("ShareCircle.Models.Vracilo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DatumVracila")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_dolznika")
                        .HasColumnType("int");

                    b.Property<int>("ID_skupine")
                        .HasColumnType("int");

                    b.Property<int>("StevilkaVracila")
                        .HasColumnType("int");

                    b.Property<float>("ZnesekVracila")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("ID_dolznika");

                    b.HasIndex("ID_skupine");

                    b.ToTable("Vracilo");
                });

            modelBuilder.Entity("ShareCircle.Models.ClanSkupine", b =>
                {
                    b.HasOne("ShareCircle.Models.Skupina", "Skupina")
                        .WithMany("ClanSkupine")
                        .HasForeignKey("ID_skupine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShareCircle.Models.Uporabnik", "Uporabnik")
                        .WithMany("ClanSkupine")
                        .HasForeignKey("ID_uporabnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skupina");

                    b.Navigation("Uporabnik");
                });

            modelBuilder.Entity("ShareCircle.Models.RazdelitevStroska", b =>
                {
                    b.HasOne("ShareCircle.Models.Uporabnik", "Dolznik")
                        .WithMany("RazdelitveStroskov")
                        .HasForeignKey("ID_dolznika")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShareCircle.Models.Strosek", "Strosek")
                        .WithMany("RazdelitveStroskov")
                        .HasForeignKey("ID_stroska")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolznik");

                    b.Navigation("Strosek");
                });

            modelBuilder.Entity("ShareCircle.Models.Strosek", b =>
                {
                    b.HasOne("ShareCircle.Models.Uporabnik", "Placnik")
                        .WithMany("Stroski")
                        .HasForeignKey("ID_placnika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShareCircle.Models.Skupina", "Skupina")
                        .WithMany("Stroski")
                        .HasForeignKey("ID_skupine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Placnik");

                    b.Navigation("Skupina");
                });

            modelBuilder.Entity("ShareCircle.Models.Vracilo", b =>
                {
                    b.HasOne("ShareCircle.Models.Uporabnik", "Dolžnik")
                        .WithMany("Vracila")
                        .HasForeignKey("ID_dolznika")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShareCircle.Models.Skupina", "Skupina")
                        .WithMany("Vracila")
                        .HasForeignKey("ID_skupine")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolžnik");

                    b.Navigation("Skupina");
                });

            modelBuilder.Entity("ShareCircle.Models.Skupina", b =>
                {
                    b.Navigation("ClanSkupine");

                    b.Navigation("Stroski");

                    b.Navigation("Vracila");
                });

            modelBuilder.Entity("ShareCircle.Models.Strosek", b =>
                {
                    b.Navigation("RazdelitveStroskov");
                });

            modelBuilder.Entity("ShareCircle.Models.Uporabnik", b =>
                {
                    b.Navigation("ClanSkupine");

                    b.Navigation("RazdelitveStroskov");

                    b.Navigation("Stroski");

                    b.Navigation("Vracila");
                });
#pragma warning restore 612, 618
        }
    }
}
